# Application
exit: control-q
escape-dispatch: escape

# Mouse
select-or-center: mouse1-click
gui-show-context-menu: mouse3-click

# Selection and tracking
follow-selected: f
sync-selected: y
track-selected: t
control-selected: shift-alt-t
goto-front: alt-d
goto-illuminated-front: shift-control-alt-d
goto-selected: g
center-selected: c
goto-north: alt-n
goto-south: shift-alt-n
goto-meridian: alt-r
align-ecliptic: alt-e
align-equatorial: alt-q
goto-surface: control-alt-g
select-home: alt-h
select-object-0: 0
select-object-1: 1
select-object-2: 2
select-object-3: 3
select-object-4: 4
select-object-5: 5
select-object-6: 6
select-object-7: 7
select-object-8: 8
select-object-9: 9

# Time
set-j2000-date: j
set-current-date: n
accelerate-time-2: page_up
accelerate-time-10: shift-page_up
slow-time-2: page_down
slow-time-10: shift-page_down
invert-time: r
toggle-freeze-time: space
set-real-time: "!"

# UI
gui-toggle-menubar: control-m
gui-search-object: control-f
toggle-fullscreen: alt-enter
gui-show-preferences: "control-,"
gui-show-editor: control-e
gui-show-info: control-i
gui-show-help: "?"
toggle-hud: h

# Camera
zoom-in: "+"
zoom-out: "-"
reset-zoom: backspace

# Rendering
toggle-hdr: f4
save-screenshot: f10
save-screenshot-no-gui: shift-f10
decrease-ambient: "alt-["
increase-ambient: "alt-]"
decrease-limit-magnitude: "["
increase-limit-magnitude: "]"
decrease-exposure: "control-["
increase-exposure: "control-]"

toggle-atmosphere: alt-a
toggle-clouds: alt-c
toggle-body-class-galaxy: alt-b

# Asterism, constellations and guides toggles
toggle-asterisms: a
toggle-constellations-boundaries: b
toggle-equatorial-grid: e
toggle-ecliptic-grid: shift-e
toggle-rotation-axis: shift-a
toggle-reference-axis: shift-control-a

# Orbits
toggle-orbits: o
toggle-orbit-star: shift-control-s
toggle-orbit-planet: shift-control-p
toggle-orbit-dwarfplanet: shift-control-d
toggle-orbit-moon: shift-control-m
toggle-orbit-minormoon: shift-control-i
toggle-orbit-comet: shift-control-k
toggle-orbit-asteroid: shift-control-a
toggle-orbit-spacecraft: shift-control-x

# Labels
toggle-label-galaxy: shift-alt-g
toggle-label-star: shift-alt-s
toggle-label-planet: shift-alt-p
toggle-label-dwarfplanet: shift-alt-d
toggle-label-moon: shift-alt-m
toggle-label-minormoon: shift-alt-i
toggle-label-comet: shift-alt-k
toggle-label-asteroid: shift-alt-a
toggle-label-spacecraft: shift-alt-x
toggle-label-constellation: shift-alt-l

# Scripts and cel url
save-cel-url: control-c
load-cel-url: control-v
open-script: control-o

# Marks
mark-selected: alt-m
unmark-selected: alt-u
unmark-all: shift-alt-u

# Debug
debug-connect-pstats: f2
debug-toggle-filled-wireframe: f3
debug-toggle-wireframe: shift-f3
debug-toggle-buffer-viewer: f5
debug-dump-octree-stats: f7
debug-dump-octree: shift-f7
debug-freeze-lod: f8
debug-dump-objects-stats: shift-f8
debug-dump-objects-info: shift-control-f8
debug-toggle-split-merge-log: control-f8
debug-toggle-shader-debug-coord: f9
debug-toggle-bounding-boxes: shift-f9
debug-toggle-lod-frustum: control-f9
debug-toggle-shadows-frustum: shift-control-f9
debug-scene-ls: f11
debug-scene-explore: control-f11
debug-scene-analyze: f12
debug-print-tasks: shift-f12
debug-toggle-jump: control-j
debug-print-info: shift-h
toggle-fly-mode: alt-y
